import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DATA_DIR = path.join(__dirname, '..', 'data');

// Modest student-room photos (basic bedsitters / hostels — not luxury interiors)
const IMG = {
  roomA: 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800&h=500&fit=crop',
  roomB: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&h=500&fit=crop',
  roomC: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800&h=500&fit=crop',
  roomD: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&h=500&fit=crop',
  shared: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&h=500&fit=crop',
  bedsitter: 'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800&h=500&fit=crop',
  hostel: 'https://images.unsplash.com/photo-1555854283-4e8f7e493bf0?w=800&h=500&fit=crop',
  corridor: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&h=500&fit=crop',
  desk: 'https://images.unsplash.com/photo-1560448204-e02f07c08d3b?w=800&h=500&fit=crop',
  kitchen: 'https://images.unsplash.com/photo-1536376072261-38c747d2c585?w=800&h=500&fit=crop',
};

const landlords = [
  {
    id: 'll-001',
    name: 'James Mwiti',
    company: 'Nchiru Comrades Housing',
    phone: '+254712345601',
    whatsapp: '254712345601',
    email: 'james@nchirucomrades.co.ke',
    photo: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=400&fit=crop',
    bio: 'Manages Green House, Blue House, and White House near Meru University main gate.',
    verified: true,
    rating: 4.8,
    totalListings: 4,
  },
  {
    id: 'll-002',
    name: 'Grace Kanana',
    company: 'Kianjai Student Hostels',
    phone: '+254723456702',
    whatsapp: '254723456702',
    email: 'grace@kianjaihostels.co.ke',
    photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=400&fit=crop',
    bio: 'Landlady for Pink House, Blessings Hostel, and Omega Apartments around Kianjai.',
    verified: true,
    rating: 4.9,
    totalListings: 3,
  },
  {
    id: 'll-003',
    name: 'Peter Kariuki',
    company: 'Nchiru Flats & Apartments',
    phone: '+254734567803',
    whatsapp: '254734567803',
    email: 'peter@nchiruapartments.co.ke',
    photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop',
    bio: 'Runs Red House, Yellow House, Panama, and Dallas — popular with MKU comrades.',
    verified: true,
    rating: 4.7,
    totalListings: 4,
  },
  {
    id: 'll-004',
    name: 'Mary Njoki',
    company: 'Budget Comrade Rooms',
    phone: '+254745678904',
    whatsapp: '254745678904',
    email: 'mary@budgetcomrades.co.ke',
    photo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop',
    bio: 'Affordable Black House, B7 Flats, and Destiny Flats for freshers on a budget.',
    verified: true,
    rating: 4.6,
    totalListings: 3,
  },
];

const listings = [
  // ——— NCHIRU (famous comrade houses) ———
  {
    id: 'prop-001',
    landlordId: 'll-001',
    title: 'Green House — Single Room',
    type: 'single',
    gender: 'any',
    price: 5000,
    deposit: 5000,
    location: 'Green House, Nchiru (near main gate)',
    distanceToCampus: '5 min walk',
    amenities: ['Water', 'Electricity', 'Security', 'Shared kitchen'],
    images: [IMG.roomA, IMG.kitchen],
    available: 3,
    featured: true,
    description:
      'Classic Nchiru Green House — simple single room with bed, table, and shared kitchen. Popular with MKU freshers.',
  },
  {
    id: 'prop-002',
    landlordId: 'll-001',
    title: 'Blue House — Shared Double',
    type: 'shared',
    gender: 'male',
    price: 3500,
    deposit: 3500,
    location: 'Blue House, Nchiru',
    distanceToCampus: '7 min walk',
    amenities: ['Water', 'Electricity', 'Shared bathroom', 'Study desk'],
    images: [IMG.shared, IMG.roomB],
    available: 4,
    featured: true,
    description:
      'Blue House shared room for two comrades. Basic furniture, friendly vibe — split rent and save.',
  },
  {
    id: 'prop-003',
    landlordId: 'll-001',
    title: 'White House — Single Room',
    type: 'single',
    gender: 'any',
    price: 4500,
    deposit: 4500,
    location: 'White House, Nchiru',
    distanceToCampus: '8 min walk',
    amenities: ['Water', 'Electricity', 'Shared kitchen', 'Security'],
    images: [IMG.roomC, IMG.corridor],
    available: 2,
    featured: true,
    description:
      'White House single — clean comrade room, quiet block. Walking distance to lectures.',
  },
  {
    id: 'prop-004',
    landlordId: 'll-001',
    title: 'Black House — Economy Single',
    type: 'single',
    gender: 'male',
    price: 3000,
    deposit: 3000,
    location: 'Black House, Nchiru',
    distanceToCampus: '10 min walk',
    amenities: ['Water', 'Electricity', 'Shared bathroom'],
    images: [IMG.roomD],
    available: 5,
    featured: false,
    description:
      'Most affordable room in Nchiru — no frills, just a bed and space to study. Ideal for tight budgets.',
  },
  {
    id: 'prop-005',
    landlordId: 'll-003',
    title: 'Red House — Bedsitter',
    type: 'bedsitter',
    gender: 'any',
    price: 5500,
    deposit: 5500,
    location: 'Red House, Nchiru (MIT side)',
    distanceToCampus: '6 min walk',
    amenities: ['Water', 'Electricity', 'Private bathroom', 'Small kitchen'],
    images: [IMG.bedsitter, IMG.roomB],
    available: 2,
    featured: true,
    description:
      'Red House bedsitter — self-contained comrade cube near MIT hostels. Own bathroom, basic kitchen.',
  },
  {
    id: 'prop-006',
    landlordId: 'll-003',
    title: 'Yellow House — Shared Room',
    type: 'shared',
    gender: 'any',
    price: 3200,
    deposit: 3200,
    location: 'Yellow House, Nchiru',
    distanceToCampus: '9 min walk',
    amenities: ['Water', 'Electricity', 'Shared kitchen', 'Borehole water'],
    images: [IMG.shared, IMG.kitchen],
    available: 6,
    featured: true,
    description:
      'Yellow House — comrades share a room and costs. Common choice for first-years from the same county.',
  },
  {
    id: 'prop-007',
    landlordId: 'll-003',
    title: 'Panama Apartments — Single',
    type: 'single',
    gender: 'male',
    price: 4800,
    deposit: 4800,
    location: 'Panama Apartments, Nchiru',
    distanceToCampus: '8 min walk',
    amenities: ['Water', 'Electricity', 'Security', 'Shared kitchen'],
    images: [IMG.roomA, IMG.desk],
    available: 3,
    featured: false,
    description:
      'Panama block — neat single rooms, metal bed and study table. Gated compound with watchman.',
  },
  {
    id: 'prop-008',
    landlordId: 'll-003',
    title: 'Dallas House — Ladies Hostel Wing',
    type: 'hostel',
    gender: 'female',
    price: 6000,
    deposit: 6000,
    location: 'Dallas House, Nchiru',
    distanceToCampus: '10 min boda',
    amenities: ['Water', 'Electricity', 'Curfew', 'Shared bathroom', 'Laundry area'],
    images: [IMG.hostel, IMG.corridor],
    available: 4,
    featured: true,
    description:
      'Dallas House ladies wing — dorm-style rooms, common washrooms. Safe and familiar for female comrades.',
  },
  {
    id: 'prop-009',
    landlordId: 'll-004',
    title: 'B7 Flats — Shared (2 per room)',
    type: 'shared',
    gender: 'any',
    price: 2800,
    deposit: 2800,
    location: 'B7 Flats, Nchiru',
    distanceToCampus: '12 min walk',
    amenities: ['Water', 'Electricity', 'Shared kitchen'],
    images: [IMG.shared, IMG.roomC],
    available: 8,
    featured: true,
    description:
      'B7 Flats — cheapest share in Nchiru. Two comrades per room, bring your own mattress if needed.',
  },
  {
    id: 'prop-010',
    landlordId: 'll-004',
    title: 'Havana House — Single Room',
    type: 'single',
    gender: 'male',
    price: 4200,
    deposit: 4200,
    location: 'Havana House, Nchiru',
    distanceToCampus: '11 min walk',
    amenities: ['Water', 'Electricity', 'Shared bathroom', 'Security'],
    images: [IMG.roomB, IMG.desk],
    available: 2,
    featured: false,
    description:
      'Havana — small but solid single. Comrades like it for night prep before cats.',
  },
  // ——— KIANJAI ———
  {
    id: 'prop-011',
    landlordId: 'll-002',
    title: 'Pink House Kianjai — Single Room',
    type: 'single',
    gender: 'female',
    price: 4000,
    deposit: 4000,
    location: 'Pink House, Kianjai',
    distanceToCampus: '15 min boda',
    amenities: ['Water', 'Electricity', 'Shared kitchen', 'Security'],
    images: [IMG.roomD, IMG.kitchen],
    available: 3,
    featured: true,
    description:
      'Pink House in Kianjai — affordable for comrades who prefer Kianjai route. Simple room, shared facilities.',
  },
  {
    id: 'prop-012',
    landlordId: 'll-002',
    title: 'Blessings Hostel Kianjai',
    type: 'hostel',
    gender: 'female',
    price: 5500,
    deposit: 5500,
    location: 'Blessings Hostel, Kianjai',
    distanceToCampus: '12 min boda',
    amenities: ['Water', 'Electricity', 'Study room', 'Shared bathroom', 'Prayer allowed'],
    images: [IMG.hostel, IMG.roomC],
    available: 5,
    featured: true,
    description:
      'Blessings Hostel — quiet Kianjai hostel for ladies. Bunk-style or single beds, comrade-friendly rules.',
  },
  {
    id: 'prop-013',
    landlordId: 'll-002',
    title: 'Omega Apartments Kianjai — Bedsitter',
    type: 'bedsitter',
    gender: 'any',
    price: 5000,
    deposit: 5000,
    location: 'Omega Apartments, Kianjai',
    distanceToCampus: '14 min boda',
    amenities: ['Water', 'Electricity', 'Private bathroom', 'Kitchen corner'],
    images: [IMG.bedsitter, IMG.roomA],
    available: 2,
    featured: false,
    description:
      'Omega — small bedsitter in Kianjai for comrades who want a bit of privacy off the main Nchiru strip.',
  },
  {
    id: 'prop-014',
    landlordId: 'll-004',
    title: 'Destiny Flats Kianjai — Shared',
    type: 'shared',
    gender: 'any',
    price: 3000,
    deposit: 3000,
    location: 'Destiny Flats, Kianjai',
    distanceToCampus: '16 min boda',
    amenities: ['Water', 'Electricity', 'Shared kitchen', 'Parking for bodas'],
    images: [IMG.corridor, IMG.shared],
    available: 4,
    featured: true,
    description:
      'Destiny Flats Kianjai — share with a roommate, low rent. Good for comrades from Maua / Kianjai side.',
  },
];

const testimonials = [
  {
    id: 't-1',
    name: 'Brian M.',
    course: 'BSc Computer Science, Year 1',
    text: 'Found my room in one day through NyumbaHub. Paid deposit via M-Pesa and moved in the same week!',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
    rating: 5,
  },
  {
    id: 't-2',
    name: 'Faith W.',
    course: 'BEd Arts, Year 1',
    text: 'The WhatsApp link connected me directly to my landlord. No middlemen, no stress.',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop',
    rating: 5,
  },
  {
    id: 't-3',
    name: 'Kevin O.',
    course: 'BCom, Year 2',
    text: 'I got a room at Green House through NyumbaHub. Photos looked like real comrade rooms, not fake luxury pics!',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop',
    rating: 5,
  },
];

const faqs = [
  {
    id: 'faq-1',
    question: 'How do I apply for a house on NyumbaHub?',
    answer: 'Browse listings, open a property you like, click Apply Now, fill in your student details, and submit. You will receive a reference number to track your application.',
  },
  {
    id: 'faq-2',
    question: 'Can I pay rent through the portal?',
    answer: 'Yes. After your application is approved, use the Pay Rent section with M-Pesa. Enter your phone number and confirm the STK push on your phone.',
  },
  {
    id: 'faq-3',
    question: 'How do I contact a landlord?',
    answer: 'Every listing shows the landlord profile with a WhatsApp button. Tap it to chat directly about viewing the house.',
  },
  {
    id: 'faq-4',
    question: 'Is NyumbaHub affiliated with Meru University?',
    answer: 'NyumbaHub is an independent platform built to help Meru University students find verified off-campus housing in Nchiru, Kianjai, and nearby estates.',
  },
  {
    id: 'faq-5',
    question: 'What documents do I need?',
    answer: 'Your admission letter or student ID, parent/guardian contact, and M-Pesa for deposit payment after approval.',
  },
];

if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, { recursive: true });

fs.writeFileSync(path.join(DATA_DIR, 'landlords.json'), JSON.stringify(landlords, null, 2));
fs.writeFileSync(path.join(DATA_DIR, 'listings.json'), JSON.stringify(listings, null, 2));
fs.writeFileSync(path.join(DATA_DIR, 'applications.json'), JSON.stringify([], null, 2));
fs.writeFileSync(path.join(DATA_DIR, 'payments.json'), JSON.stringify([], null, 2));
fs.writeFileSync(path.join(DATA_DIR, 'testimonials.json'), JSON.stringify(testimonials, null, 2));
fs.writeFileSync(path.join(DATA_DIR, 'faqs.json'), JSON.stringify(faqs, null, 2));

console.log('NyumbaHub database seeded successfully.');
